// <auto-generated />
using System;
using ASP.NET_Projekt_Wypozyczalnia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_Projekt_Wypozyczalnia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309135624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.Klient", b =>
                {
                    b.Property<int>("IDKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDKlienta"));

                    b.Property<string>("AdresZamieszkania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerDokumentu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypDokumentu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDKlienta");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.PozycjaWypozyczenia", b =>
                {
                    b.Property<int>("IDWypozyczenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDWypozyczenia"));

                    b.Property<DateTime>("DataPrzewidywanaZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDKlienta")
                        .HasColumnType("int");

                    b.Property<int>("IDSamochodu")
                        .HasColumnType("int");

                    b.Property<string>("StatusWynajmu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDWypozyczenia");

                    b.HasIndex("IDKlienta");

                    b.HasIndex("IDSamochodu");

                    b.ToTable("PozycjeWypozyczenia");
                });

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.Samochod", b =>
                {
                    b.Property<int>("IDSamochodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSamochodu"));

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerRejestracyjny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PojemnoscSilnika")
                        .HasColumnType("int");

                    b.Property<int>("Przebieg")
                        .HasColumnType("int");

                    b.Property<string>("RodzajPaliwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TerminPrzegladu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TerminUbezpieczenia")
                        .HasColumnType("datetime2");

                    b.HasKey("IDSamochodu");

                    b.ToTable("Samochody");
                });

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.PozycjaWypozyczenia", b =>
                {
                    b.HasOne("ASP.NET_Projekt_Wypozyczalnia.Models.Klient", "Klient")
                        .WithMany("PozycjeWypozyczenia")
                        .HasForeignKey("IDKlienta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Projekt_Wypozyczalnia.Models.Samochod", "Samochod")
                        .WithMany("PozycjeWypozyczenia")
                        .HasForeignKey("IDSamochodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Samochod");
                });

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.Klient", b =>
                {
                    b.Navigation("PozycjeWypozyczenia");
                });

            modelBuilder.Entity("ASP.NET_Projekt_Wypozyczalnia.Models.Samochod", b =>
                {
                    b.Navigation("PozycjeWypozyczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
